# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values # Taking all rows and columns starting from the fourth until the one before last
y = dataset.iloc[:, -1].values # Vector that will contain the column of the dependent variable

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) # Transform the gender column. It will encode them into 0 and 1 classes

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') # Perform One Hot Encoding for the second column (the geography column)
X = np.array(ct.fit_transform(X)) # Remember: the One hot encoded variable will be moved to the beginning of the matrix


In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
# Feature Sacling is mandatory for any deep learning, and it should be done for all features regardless of how their values look like
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # Sacling applied to all features 
X_test = sc.transform(X_test) # For the test set apply the scaler (already fitted to the training set)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
# Build an Artificial Neural Network as a sequence of layers (Sequential model from Keras). Since TensorFlow 2.0 keras became a part of TensorFlow
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
# Add a fully connected layer (first layer in the deep neural network). Dense class creates a fully connected layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # units is the number of neurons in the layer. The value 6
# is just a magic number that was determined by experimentation (there is no thinking behind, only trial and error). activation is the
# the activation function applied at the neurons of the layer. For hidden layers, the rectifier function is used (shortname is 'relu')

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # Exactly the same line as the first layer (with the same number of neurons = 6)

### Adding the output layer

In [ ]:
# The output layer: Since we have a binary value for the output (dependent variable) 0/1, we need only one neuron at the output layer 
# For the activation function at the output layer, we used the Sigmoid function as activation function, because not only we get the binary value
# But also the probability of having this value (the probability of the customer leaving the bank). Sigmoid is used because the dependent variable is binary.
# If the dependent variable is not binary, then the activation function should be 'softmax'
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
# The compile method configures the ann model. the optimizer parameter chooses which optimizer to adjust the neural network
# weights. The 'adam' optimizer uses Stochastic Gradient Descent.
# Since the dependent variable is binary, the loss function should be 'binary_crossentropy'. If the dependent variable
# is not binary, then the loss function should be 'categorical_crossentropy'
# metrics parameter contains the list of metrics used to evaluate the neural network 

ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
# We are training using batch learning, (entering batches of input data to do forward and backpropagation using the Stochastic Gradient Descent)
# A batch size of 32 is very commonly used
# epochs: the number of times the full dataset is entered into the neural network. Choose any number, but make sure it's large
# enough so that the network can properly learn and find correlations. 100 is just a magic number
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.8623 - accuracy: 0.3795
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5545 - accuracy: 0.7926
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4843 - accuracy: 0.7978
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4722 - accuracy: 0.7907
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4496 - accuracy: 0.7978
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4420 - accuracy: 0.7977
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.8027
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4234 - accuracy: 0.8066
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3965 - accuracy: 0.8226
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3993 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
# Remember: The encoding of 'France' using One Hot Encoding was: 1 0 0. This should be entered instead of the string 'France'
# and male is encoded (using Label Encoder) is 1
# Remember: the same scaling that was applied to the training and testing sets should be applied to the input. Hence the use of the sc object.
# Make sure you are only calling transform (and not fit_transform because fitting should only be applied to the training set)
# predict method returns a probability, we defined a threshold of staying/leaving the bank of 0.5
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) # converted the predicted probabilities into 1 (if > 0.5 threshold) or 0 otherwise
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)) # Show the prediction of the test set side by side with the actual values of the test set

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
# Show the confusion matrix and the the accuracy score for the predictions of the test set.
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 200  205]]


0.8605